bbs/urls.py
from django.urls import path
from . import views

app_name    = "bbs"
urlpatterns = [ 
    path('', views.index, name="index"),
    path('trend', views.trend, name="trend"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("bbs.urls"), name="bbs"),
]

bbs/models.py
from django.db import models
from django.utils import timezone

class Topic(models.Model):

    class Meta:
        db_table = "topic"

    comment = models.CharField(verbose_name="コメント",max_length=2000)
    dt      = models.DateTimeField(verbose_name="投稿日",default=timezone.now)

    def __str__(self):
        return self.comment


class Trend(models.Model):

    class Meta:
        db_table = "trend"

    word    = models.CharField(verbose_name="トレンドワード",max_length=2000)
    count   = models.IntegerField(verbose_name="出現回数",default=0)
    dt      = models.DateTimeField(verbose_name="投稿日",default=timezone.now)

    def __str__(self):
        return self.word

bbs/forms.py
from django import forms
from .models import Topic,Trend

class TopicForm(forms.ModelForm):

    class Meta:
        model   = Topic
        fields  = [ "comment" ]

class TrendForm(forms.ModelForm):

    class Meta:
        model   = Trend
        fields  = [ "word","count" ]

bbs/views.py
from django.shortcuts import render,redirect

from django.views import View
from django.db.models import Q

from .models import Topic,Trend
from .forms import TopicForm

class BbsView(View):

    def get(self, request, *args, **kwargs):

        context     = {}

        if "search" in request.GET:
            search      = request.GET["search"]

            if search == "" or search.isspace():
                return redirect("bbs:index")

            search      = search.replace("　"," ").split(" ")
            searches    = [ w for w in search if w != "" ]

            query       = Q() 
            for w in searches:
                query &= Q(comment__contains=w)

            #(4)作ったクエリを実行
            context["topics"]   = Topic.objects.filter(query)
        else:
            context["topics"]   = Topic.objects.all()

        return render(request,"bbs/index.html",context)

    def post(self, request, *args, **kwargs):

        form    = TopicForm(request.POST)

        if form.is_valid():
            print("OK")
            form.save()

        return redirect("bbs:index")

index   = BbsView.as_view()

class TrendView(View):

    def get(self, request, *args, **kwargs):

        context             = {}
        context["trends"]   = Trend.objects.all().order_by("-count")[:150]

        return render(request,"bbs/trend.html",context)

trend   = TrendView.as_view()

templates/bbs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
	<title>簡易掲示板</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    {% block extra_head %}
    {% endblock %}

</head>
<body>
    <h1 class="bg-primary"><a class="text-white" href="{% url 'bbs:index' %}">簡易掲示板</a></h1>

    <main class="container">
        {% block main %}
        {% endblock %}
    </main>
</body>
</html>

templates/bbs/index.html
{% extends "bbs/base.html" %}

{% block extra_head %}
{% endblock %}

{% block main %}

<a style="font-size:2rem;" href="{% url 'bbs:trend' %}">トレンド</a>

<form>
    <input class="" type="text" name="search" placeholder="検索ワード" value="{{ request.GET.search }}">
    <input class="btn btn-primary" type="submit" value="検索">
</form>

<form method="POST">
    {% csrf_token %}
    <textarea class="form-control" name="comment"></textarea>
    <input type="submit" value="送信">
</form>

{% for topic in topics %}
<div class="border p-1">
    <div style="font-size:1.1rem;padding:0.5rem;">{{ topic.comment }}</div>
    <div style="font-size:0.9rem;font-weight:bold;">{{ topic.dt }}</div>
</div>
{% endfor %}
{% endblock %}

templates/bbs/trend.html
{% extends "bbs/base.html" %}

{% block extra_head %}
{% endblock %}

{% block main %}

<h2 style="text-shadow:2px 2px 2px gray;">トレンドワード</h2>

{% for trend in trends %}
<a class="" style="font-size:2rem;" href="{% url 'bbs:index' %}?search={{ trend.word }}" >{{ trend.word }}</a>
{% endfor %}

{% endblock %}